# Site settings
title: "Becaming is better than being"
header-img: img/home-bg.png
email: dereje88@gmail.com
copyright_name: kade042
description: > # this means to ignore newlines until "baseurl:"
   ""
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  kade042
learn_profile: kade042
email_username: dereje88@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
